# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

SALT_MASTER_IP = "192.168.51.10"
CFY_MINION_IP = "192.168.51.11"
# The host machine is available to the Vagrant box at 10.0.2.2
PLUGIN_SERVING_HOST = "10.0.2.2"
SALT_MASTER_CPUS = 1
SALT_MASTER_MEMORY = 512
CFY_MINION_CPUS = 2
CFY_MINION_MEMORY = 2048

CFY_BOX = "cloudify-3.1.0-ga-b85"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box_check_update = false

    config.vm.define "salt-master" do |salt|
        salt.vm.box = "ubuntu/trusty64"
        salt.vm.hostname = "salt-master"
        salt.vm.provider "virtualbox" do |vb|
            vb.cpus = "#{SALT_MASTER_CPUS}"
            vb.memory = "#{SALT_MASTER_MEMORY}"
        end
        salt.vm.network :private_network, ip: "#{SALT_MASTER_IP}"
        salt.vm.provision :shell, path: "provision_salt_master.sh"
    end

    config.vm.define "cfy-minion", primary: true do |cfy|
        cfy.vm.box = "#{CFY_BOX}"
        cfy.vm.hostname = "cfy-minion"
        cfy.vm.provider "virtualbox" do |vb|
            vb.cpus = "#{CFY_MINION_CPUS}"
            vb.memory = "#{CFY_MINION_MEMORY}"
        end
        cfy.vm.network :private_network, ip: "#{CFY_MINION_IP}"
        cfy.vm.provision :shell, inline: "echo -e '\\n#{PLUGIN_SERVING_HOST} plugin-serving-host\\n#{SALT_MASTER_IP} salt-master' | tee -a /etc/hosts"
        cfy.vm.provision :shell, inline: "echo Waiting until Cloudify REST server is ready...; sleep 20"
        cfy.vm.provision :shell, privileged: false, path: "deploy_test_blueprint.sh"
    end

end
